//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THelper.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("THelper.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Modules&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;NewVersionServer&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;EnableDiagnosticActions&quot; value=&quot;False&quot;/&gt;
        ///    &lt;!--
        ///    Use the one of predefined values: None, ApplicationFolder, CurrentUserApplicationDataFolder. The default value is ApplicationFolder.
        ///    &lt;add key=&quot;TraceLogLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot;UserModelDiffsLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppConfigWrong2 {
            get {
                return ResourceManager.GetString("AppConfigWrong2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Modules&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;NewVersionServer&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;EnableDiagnosticActions&quot; value=&quot;False&quot;/&gt;
        ///    &lt;!--
        ///    Use the one of predefined values: None, ApplicationFolder, CurrentUserApplicationDataFolder. The default value is ApplicationFolder.
        ///    &lt;add key=&quot;TraceLogLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot;UserModelDiffsLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppConfigWrong3 {
            get {
                return ResourceManager.GetString("AppConfigWrong3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Modules&quot; value=&quot;&quot; /&gt;
        ///    &lt;add key=&quot;NewVersionServer&quot; value=&quot;&quot; /&gt;
        ///    &lt;add key=&quot;EnableDiagnosticActions&quot; value=&quot;False&quot; /&gt;
        ///    &lt;!--
        ///    Use the one of predefined values: None, ApplicationFolder, CurrentUserApplicationDataFolder. The default value is ApplicationFolder.
        ///    &lt;add key=&quot;TraceLogLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot;UserModelDiffsLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add ke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppConfigWrong3Correct {
            get {
                return ResourceManager.GetString("AppConfigWrong3Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Modules&quot; value=&quot;&quot; /&gt;
        ///    &lt;add key=&quot;NewVersionServer&quot; value=&quot;&quot; /&gt;
        ///    &lt;add key=&quot;EnableDiagnosticActions&quot; value=&quot;False&quot; /&gt;
        ///    &lt;!--
        ///    Use the one of predefined values: None, ApplicationFolder, CurrentUserApplicationDataFolder. The default value is ApplicationFolder.
        ///    &lt;add key=&quot;TraceLogLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot;UserModelDiffsLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add ke [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppRight {
            get {
                return ResourceManager.GetString("AppRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;EasyTestConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TestXAFApplicationEasyTest&quot;,
        ///    &quot;xOldConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TestXAFApplication&quot;,
        ///    &quot;ConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=dxT598706usr&quot;
        ///  },
        ///  &quot;Logging&quot;: {
        ///    &quot;LogLevel&quot;: {
        ///      &quot;Default&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appRight1 {
            get {
                return ResourceManager.GetString("appRight1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;connectionStrings&quot;: {
        ///    &quot;Prod-JasonSQL2019STANDARDTimeZoneOffsetTest&quot;: &quot;XpoProvider=MSSqlServer;data source=Prod-Jason\\SQL2019STANDARD;integrated security=SSPI;initial catalog=TimeZoneOffsetTest&quot;
        ///  }
        ///}.
        /// </summary>
        internal static string AppSettingsWrong2 {
            get {
                return ResourceManager.GetString("AppSettingsWrong2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;EasyTestConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TimeZoneOffsetTestEasyTest&quot;,
        ///    &quot;ConnectionString2&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=d286-dxT1107307usr&quot;
        ///  },
        ///  &quot;Authentication&quot;: {
        ///    &quot;Jwt&quot;: {
        ///      &quot;Issuer&quot;: &quot;XafSecurity&quot;,
        ///      &quot;Audience&quot;: &quot;http://localhost:4200&quot;,
        ///      &quot;IssuerSigningKey&quot;: &quot;3376502a-d683-47bc-91a9-09fe8f8ac2b4&quot;
        ///    }, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppSettingsWrong3 {
            get {
                return ResourceManager.GetString("AppSettingsWrong3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;EasyTestConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TimeZoneOffsetTestEasyTest&quot;,
        ///    &quot;ConnectionString2&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=d286-dxT1107307usr&quot;,
        ///    &quot;ConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=dxT598706usr&quot;
        ///  },
        ///  &quot;Authentication&quot;: {
        ///    &quot;Jwt&quot;: {
        ///      &quot;Issuer&quot;:  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppSettingsWrong3Correct {
            get {
                return ResourceManager.GetString("AppSettingsWrong3Correct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot;?&gt;
        ///&lt;configuration&gt;
        ///  &lt;appSettings&gt;
        ///    &lt;add key=&quot;Modules&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;NewVersionServer&quot; value=&quot;&quot;/&gt;
        ///    &lt;add key=&quot;EnableDiagnosticActions&quot; value=&quot;False&quot;/&gt;
        ///    &lt;!--
        ///    Use the one of predefined values: None, ApplicationFolder, CurrentUserApplicationDataFolder. The default value is ApplicationFolder.
        ///    &lt;add key=&quot;TraceLogLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot;UserModelDiffsLocation&quot; value=&quot;CurrentUserApplicationDataFolder&quot;/&gt;
        ///    &lt;add key=&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AppWrong {
            get {
                return ResourceManager.GetString("AppWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;ConnectionStrings&quot;: {
        ///    &quot;ConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TestXAFApplication&quot;,
        ///    &quot;EasyTestConnectionString&quot;: &quot;Integrated Security=SSPI;Pooling=false;Data Source=(localdb)\\mssqllocaldb;Initial Catalog=TestXAFApplicationEasyTest&quot;
        ///  },
        ///  &quot;Logging&quot;: {
        ///    &quot;LogLevel&quot;: {
        ///      &quot;Default&quot;: &quot;Information&quot;,
        ///      &quot;Microsoft&quot;: &quot;Warning&quot;,
        ///      &quot;Microsoft.Hosting.Lifetime&quot;: &quot;Information&quot;,
        ///      &quot;DevExpress.ExpressApp&quot;: &quot;Inf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string appWrong1 {
            get {
                return ResourceManager.GetString("appWrong1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project ToolsVersion=&quot;4.0&quot; DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;x86&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.30703&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{15A0B679-5A23-4E98-9BEC-E934DC0B8CF3}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputType&gt;        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string dxSampleGrid {
            get {
                return ResourceManager.GetString("dxSampleGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Project DefaultTargets=&quot;Build&quot; xmlns=&quot;http://schemas.microsoft.com/developer/msbuild/2003&quot; ToolsVersion=&quot;15.0&quot;&gt;
        ///  &lt;PropertyGroup&gt;
        ///    &lt;Configuration Condition=&quot; &apos;$(Configuration)&apos; == &apos;&apos; &quot;&gt;Debug&lt;/Configuration&gt;
        ///    &lt;Platform Condition=&quot; &apos;$(Platform)&apos; == &apos;&apos; &quot;&gt;AnyCPU&lt;/Platform&gt;
        ///    &lt;ProductVersion&gt;8.0.50727&lt;/ProductVersion&gt;
        ///    &lt;SchemaVersion&gt;2.0&lt;/SchemaVersion&gt;
        ///    &lt;ProjectGuid&gt;{0198D442-FAD7-4D8C-9D97-E4B8B4ADD8E6}&lt;/ProjectGuid&gt;
        ///    &lt;OutputType&gt;WinExe&lt;/OutputTy [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string OldFramework {
            get {
                return ResourceManager.GetString("OldFramework", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.26430.6
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;)=&quot;dxT999999.Win&quot;,&quot;dxT999999.Win\dxT999999.Win.csproj&quot;,&quot;{D05D93DF-312D-4D4E-B980-726871EC7833}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;)=&quot;dxT999999.Web&quot;,&quot;dxT999999.Web\dxT999999.Web.csproj&quot;,&quot;{82A6DBC9-B1B4-44E4-9718-55DF930CD349}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string RightSln {
            get {
                return ResourceManager.GetString("RightSln", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;Versions&gt;
        ///  &lt;AllVersions&gt;
        ///    &lt;Version Version=&quot;21.1.2005&quot; /&gt;
        ///    &lt;Version Version=&quot;20.2.2005&quot; /&gt;
        ///    &lt;Version Version=&quot;20.2.5&quot; /&gt;
        ///    &lt;Version Version=&quot;20.2.4&quot; /&gt;
        ///    &lt;Version Version=&quot;20.2.3&quot; /&gt;
        ///    &lt;Version Version=&quot;20.2.2&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.2005&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.10&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.9&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.8&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.7&quot; /&gt;
        ///    &lt;Version Version=&quot;20.1.6&quot; /&gt;
        ///    &lt;Version Version=&quot;20. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string versions {
            get {
                return ResourceManager.GetString("versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Microsoft Visual Studio Solution File, Format Version 12.00
        ///# Visual Studio 15
        ///VisualStudioVersion = 15.0.26430.6
        ///MinimumVisualStudioVersion = 10.0.40219.1
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;) = &quot;dxT999999.Module&quot;, &quot;dxT999999.Module\dxT999999.Module.csproj&quot;, &quot;{5F15837D-D1E5-44DC-92F0-4F2EBE9C3F8D}&quot;
        ///EndProject
        ///Project(&quot;{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}&quot;)=&quot;dxT999999.Module.Win&quot;,&quot;dxT999999.Module.Win\dxT999999.Module.Win.csproj&quot;,&quot;{7964F87D-BC5D-4C4E-8B2F-71E89739AA97}&quot;
        ///EndProject
        ///Pr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WrongSln {
            get {
                return ResourceManager.GetString("WrongSln", resourceCulture);
            }
        }
    }
}
