//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\WinRAR\\WinRAR.exe")]
        public string WinRarPath {
            get {
                return ((string)(this["WinRarPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\corp\\internal\\common\\4Kozhevnikov\\Deploy\\DXConverterDeploy\\DXConverter.exe")]
        public string DXConverterPath {
            get {
                return ((string)(this["DXConverterPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\corp\\internal\\common\\4Kozhevnikov\\Deploy\\DXConverterDeploy\\versions.xml")]
        public string FileWithVersionsPath {
            get {
                return ((string)(this["FileWithVersionsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("172")]
        public int LastReleasedVersion {
            get {
                return ((int)(this["LastReleasedVersion"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"  <InstalledVersions>
    <Version Version=""17.2.1"" Path=""C:\Program Files (x86)\DevExpress 17.2\Components\Tools\Components\ProjectConverter-console.exe"" />
    <Version Version=""17.1.7"" Path=""C:\Program Files (x86)\DevExpress 17.1\Components\Tools\Components\ProjectConverter-console.exe"" />
    <Version Version=""16.2.10"" Path=""C:\Program Files (x86)\DevExpress 16.2\Components\Tools\Components\ProjectConverter-console.exe"" />
  </InstalledVersions>")]
        public string InstalledVersions {
            get {
                return ((string)(this["InstalledVersions"]));
            }
        }
    }
}
