//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace THelper.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Program Files\\WinRAR\\WinRAR.exe")]
        public string WinRarPath {
            get {
                return ((string)(this["WinRarPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\corp\\internal\\common\\4Kozhevnikov\\Deploy\\DXConverterDeploy\\DXConverter.exe")]
        public string DXConverterPath {
            get {
                return ((string)(this["DXConverterPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\\\corp\\internal\\common\\4Kozhevnikov\\Deploy\\DXConverterDeploy\\versions.xml")]
        public string FileWithVersionsPath {
            get {
                return ((string)(this["FileWithVersionsPath"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("202")]
        public int LastReleasedVersion {
            get {
                return ((int)(this["LastReleasedVersion"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Logo.png;csproj.bak;ExpressAppLogo.png")]
        public string NamesToExclude {
            get {
                return ((string)(this["NamesToExclude"]));
            }
            set {
                this["NamesToExclude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("doc;docx;pdf;jpg;png;swf;gif;bak;mp4")]
        public string FilesToDetect {
            get {
                return ((string)(this["FilesToDetect"]));
            }
            set {
                this["FilesToDetect"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("v4.5.2")]
        public string FrameworkVersion {
            get {
                return ((string)(this["FrameworkVersion"]));
            }
            set {
                this["FrameworkVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\Dropbox\\")]
        public string DropboxPath {
            get {
                return ((string)(this["DropboxPath"]));
            }
            set {
                this["DropboxPath"] = value;
            }
        }
    }
}
